var = input("Digite algo: ")
print ("O tipo primitivo desse valor é ", type(var))
print ("Só tem espaços?", var.isspace())
print ("Só tem números?",var.isnumeric())
print ("É alfabético?", var.isalpha())
print ("É alfanumérico?", var.isalnum())
print ("É maiuscula?",var.isupper())
print ("É minústula?",var.islower())
print ("Está capitalizada?",var.istitle())
